#!/usr/bin/env python3
"""Generate Mobile Commons-like platform research files."""

import csv
from collections import Counter

# 100 platforms similar to Mobile Commons (advocacy/civic mobile engagement + mass SMS)
PLATFORMS = [
    # Core mobile advocacy CRM peers (direct mcommons category)
    (1, "Mobile Commons (Upland Mobile Messaging)", "https://www.mobilecommons.com", "https://app.mobilecommons.com",
     "Mobile advocacy CRM;Mass SMS broadcast;Text-to-action;Call-your-legislator;Polling locator", "NO", "YES",
     "Reference platform; zipdo nonprofit advocacy; selecthub mcommons alternatives"),
    (2, "Upland Mobile Messaging", "https://uplandsoftware.com/mobile-messaging/", "https://uplandsoftware.com/mobile-messaging/",
     "Mobile advocacy CRM;Mass SMS/MMS;Keyword opt-in;Legislative call routing", "NO", "YES",
     "Upland product page; parent of Mobile Commons"),
    (3, "Ascend (formerly Strive Messaging)", "https://www.ascendmessaging.org", "https://app.ascendmessaging.org",
     "Broadcast SMS;Call-your-legislator;P2P inbox;Instagram automations;Advocacy chatbots", "NO", "YES",
     "mcommons competitor search; yeptext strive review; ascendmessaging.org"),
    (4, "Tatango", "https://www.tatango.com", "https://app.tatango.com",
     "Nonprofit SMS broadcast;Text-to-give;Advocacy segmentation;Short code", "NO", "YES",
     "tatango.com nonprofit; rallycorp comparison; emitrr nonprofit texting guide"),
    (5, "Rally Corp", "https://www.rallycorp.com", "https://app.rallycorp.com",
     "Advocacy SMS broadcast;P2P texting;Text-to-give;RCS messaging;Keyword opt-in", "YES", "YES",
     "rallycorp advocacy SMS; emitrr nonprofit guide; frontstream broadcast vs P2P"),
    (6, "EveryAction (Bonterra)", "https://www.bonterratech.com/product/everyaction", "https://secure.everyaction.com",
     "Mobile messaging add-on;Advocacy forms;Broadcast SMS;Supporter CRM", "NO", "YES",
     "muster advocacy software; bonterra mobile messaging help docs"),
    (7, "Salsa Engage (Bonterra)", "https://www.salsalabs.com", "https://secure.salsalabs.com",
     "Broadcast text messages;Advocacy targeted actions;Supporter CRM", "NO", "YES",
     "bonterra salsa blog; engaging networks salsa comparison"),
    (8, "Bonterra Fundraising & Engagement", "https://www.bonterratech.com", "https://secure.everyaction.com",
     "Integrated SMS/MMS;Advocacy mobilization;Mobile opt-in;Volunteer SMS", "NO", "YES",
     "bonterra pricing mobile messaging; salsa sunset migration"),
    (9, "Muster", "https://www.muster.com", "https://app.muster.com",
     "Advocacy CRM;Email and text broadcasts;Mobile action centers;Legislative targeting", "NO", "YES",
     "muster.com advocacy software 2026; zipdo nonprofit advocacy"),
    (10, "Quorum Grassroots", "https://www.quorum.us/products/grassroots/", "https://app.quorum.us",
     "Advocacy SMS;Tap-to-act mobile action centers;Advocate CRM;Patch-through calls", "NO", "YES",
     "quorum grassroots texting blog; advocacyai alternatives"),
    (11, "Capitol Canary (Phone2Action legacy)", "https://www.capitolcanary.com", "https://app.capitolcanary.com",
     "Grassroots SMS;Multi-channel advocacy;Mobile keywords;GOTV tools", "NO", "YES",
     "sourceforge votervoice compare; quorum acquires capitol canary"),
    (12, "VoterVoice (FiscalNote)", "https://www.votervoice.net", "https://app.votervoice.net",
     "SMS broadcast alerts;Mobile-first advocacy;Action center links;Association mobilization", "NO", "YES",
     "votervoice SMS help center; muster advocacy software"),
    (13, "AdvocacyAI", "https://advocacyai.com", "https://app.advocacyai.com",
     "Advocate CRM;SMS journeys;Click-to-call;Legislative targeting;GOTV tools", "NO", "YES",
     "advocacyai.com platform; go.advocacyai alternatives blog"),
    (14, "CiviClick", "https://civiclick.com", "https://app.civiclick.com",
     "Text messages and mobile keywords;Patch-through calls;Omni-channel advocacy", "NO", "YES",
     "civiclick grassroots software; nerdisa civiclick vs OCP"),
    (15, "OneClickPolitics", "https://oneclickpolitics.com", "https://app.oneclickpolitics.com",
     "Mass SMS/MMS;Mobile keywords;Short code;Patch-through calling", "NO", "YES",
     "oneclickpolitics.com; OCP text messaging setup help"),
    (16, "New/Mode", "https://www.newmode.net", "https://www.newmode.net/login",
     "Broadcast SMS actions;Multi-channel advocacy;SMS chatbot;Petition and call tools", "YES", "YES",
     "newmode SMS blog; blackbaud partner page; sourceforge votervoice compare"),
    (17, "Congress Plus Advocacy (The Soft Edge)", "https://thesoftedge.com", "https://thesoftedge.com",
     "SMS engagement;Mobile-responsive advocacy;Patch-through calling;Action centers", "NO", "YES",
     "thesoftedge.com; muster advocacy software; sourceforge compare"),
    (18, "Engaging Networks", "https://www.engagingnetworks.net", "https://e-activist.com",
     "Email and SMS broadcast;Advocacy tools;P2P fundraising;Supporter CRM", "NO", "YES",
     "engagingnetworks.net; salsa labs comparison landing page"),
    (19, "Allyz", "https://allyz.co", "https://allyz.co",
     "AllyzBot SMS activation;Web forms for legislator contact;P2P texting (planned)", "NO", "YES",
     "allyz.co text level advocacy; call-your-legislator SMS search"),
    (20, "Qomon", "https://qomon.com/us", "https://app.qomon.com",
     "Emails and SMS/MMS;Field mobile app;Advocacy CRM;Union and PAC outreach", "NO", "YES",
     "qomon.com us; civic engagement SMS CRM search"),
    (21, "Blackbaud Luminate Advocacy", "https://www.blackbaud.com/products/blackbaud-luminate-advocacy", "https://www.blackbaud.com/login",
     "Advocacy mobilization;Multi-channel legislator contact;Supporter targeting", "NO", "YES",
     "sourceforge votervoice compare; newmode blackbaud partner"),
    (22, "MobileAction! (DNL OmniMedia)", "https://www.dnlomnimedia.com/products/mobile-app/", "https://www.dnlomnimedia.com",
     "Mobile advocacy app;P2P fundraising;Luminate Online integration", "NO", "YES",
     "dnlomnimedia mobileaction; muster advocacy software"),
    (23, "SparkInfluence", "https://www.sparkinfluence.com", "https://app.sparkinfluence.com",
     "Mobile-friendly advocacy;Grassroots CRM;Multi-channel engagement", "NO", "YES",
     "sourceforge votervoice compare"),
    (24, "CQ Engage", "https://info.cq.com/cq-engage", "https://info.cq.com",
     "Grassroots advocacy;Supporter mobilization;Multi-channel calls to action", "NO", "YES",
     "sourceforge votervoice compare (CQRC Engage)"),
    (25, "Ujoin", "https://www.ujoin.co", "https://www.ujoin.co",
     "Custom action pages;Legislator email/call/tweet;Advocate segmentation", "YES", "YES",
     "sourceforge votervoice compare"),
    # Digital organizing suites (broadcast + P2P + mobile CRM overlap)
    (26, "ActBlue Field Tools (Impactive)", "https://www.impactive.io", "https://campaigns.impactive.io",
     "Broadcast texting;P2P texting;SMS fundraising;Relational organizing", "NO", "YES",
     "impactive broadcast texting; slicktext political SMS guide 2026"),
    (27, "CallHub", "https://callhub.io", "https://callhub.io/login",
     "Text broadcast;Text-to-join;P2P texting;Advocacy mass SMS;CRM sync", "YES", "YES",
     "callhub.io mass texting; muster advocacy software; mass_calling_platforms.csv"),
    (28, "Solidarity Tech", "https://www.solidarity.tech", "https://www.solidarity.tech",
     "SMS text blasts;Textbanks;Mobile field app;Advocacy CRM", "YES", "YES",
     "solidarity.tech advocacy; union organizing platform search"),
    (29, "Prompt.io", "https://prompt.io", "https://app.prompt.io",
     "Broadcast and P2P texting;Advocacy action alerts;10DLC compliance;Mobile wallet cards", "NO", "YES",
     "prompt.io advocacy; political texting page"),
    (30, "Daisychain", "https://www.daisychain.app", "https://www.daisychain.app",
     "Personalized texting at scale;Flows automation;Action Network integration", "NO", "YES",
     "daisychain.app; action network SMS alternatives search"),
    (31, "CampaignCNX+", "https://www.campaigncnx.com", "https://app.campaigncnx.com",
     "Political/advocacy SMS;GOTV;Legislative call activations;10DLC compliance", "YES", "YES",
     "campaigncnx.com political texting; call-your-legislator SMS search"),
    (32, "Zeeptext", "https://zeeptext.com", "https://app.zeeptext.com",
     "Mass texting;Keyword automation;10DLC;Nonprofit and union advocacy", "YES", "YES",
     "zeeptext.com; union SMS platform search"),
    (33, "Peerly", "https://peerly.com", "https://app.peerly.com",
     "P2P texting;Advocacy mobilization;Voter engagement;Fundraising SMS", "YES", "YES",
     "peerly.com; tatango P2P vendor list"),
    (34, "Hustle", "https://www.hustle.com", "https://app.hustle.com",
     "P2P texting;Advocacy mobilization;Supporter conversations", "NO", "YES",
     "slicktext political SMS guide; textus hustle vs ez texting"),
    (35, "RumbleUp", "https://www.rumbleup.com", "https://app.rumbleup.com",
     "P2P texting;Advocacy engagement;Large-scale voter contact", "NO", "YES",
     "slicktext political SMS guide; mass_calling_platforms.csv"),
    (36, "GetThru", "https://www.getthru.io", "https://app.getthru.io",
     "P2P texting;Conversational organizing;Volunteer-driven outreach", "NO", "YES",
     "slicktext political SMS guide"),
    (37, "Relay", "https://relaytxt.com", "https://app.relaytxt.com",
     "P2P texting;Progressive advocacy SMS", "YES", "YES",
     "mass_calling_platforms.csv; smart as a fox mobile campaign blog"),
    (38, "OpnSesame", "https://www.opnsesame.com", "https://app.opnsesame.com",
     "P2P texting;List growth;Advocacy SMS", "NO", "YES",
     "mass_calling_platforms.csv; tatango P2P vendor list"),
    (39, "ControlShift", "https://www.controlshift.app", "https://www.controlshift.app",
     "Distributed organizing;Petition campaigns;SMS integrations;Action Network sync", "YES", "YES",
     "daisychain integrations; promptloop impactive directory"),
    (40, "HubDialer", "https://hubdialer.com", "https://hubdialer.com",
     "Predictive dialer;Texting platform;Advocacy and labor outreach", "NO", "YES",
     "frontstream broadcast vs P2P (HubDial); campaignsandelections directory"),
    (41, "Grassroots Unwired", "https://www.grassrootsunwired.com", "https://www.grassrootsunwired.com",
     "Canvassing;Field organizing;Mobile advocacy workflows", "NO", "YES",
     "muster advocacy software top 10"),
    (42, "NationBuilder", "https://nationbuilder.com", "https://login.nationbuilder.com",
     "Integrated SMS;Advocacy pages;Supporter CRM;Text broadcasts", "YES", "YES",
     "muster advocacy software; zipdo nonprofit advocacy"),
    (43, "Action Network", "https://actionnetwork.org", "https://actionnetwork.org/users/sign_in",
     "Mobile-responsive actions;SMS integrations;List management;Advocacy campaigns", "YES", "YES",
     "callhub mass texting Action Network sync; daisychain integrations"),
    (44, "ActionKit (NGP VAN)", "https://www.ngpvan.com/actionkit", "https://www.ngpvan.com",
     "Progressive advocacy CRM;Mobile messaging integrations;Campaign automation", "NO", "YES",
     "muster advocacy software; impactive NGP VAN sync"),
    (45, "Blue Utopia", "https://www.blueutopia.com", "https://www.blueutopia.com",
     "Progressive CRM;Advocacy;Communications;Fundraising", "YES", "YES",
     "sourceforge votervoice compare"),
    (46, "Plus Three", "https://www.plusthree.com", "https://www.plusthree.com",
     "Advocacy platform;Online fundraising;Constituent engagement", "NO", "YES",
     "sourceforge votervoice compare"),
    (47, "PolicyEngage", "https://www.policyengage.com", "https://www.policyengage.com",
     "Grassroots advocacy widgets;Legislator connection;Digital mobilization", "NO", "YES",
     "sourceforge votervoice compare"),
    (48, "FastDemocracy", "https://www.fastdemocracy.com", "https://www.fastdemocracy.com",
     "Legislative tracking;Advocacy alerts;Policy mobilization", "YES", "YES",
     "sourceforge votervoice compare"),
    (49, "Ecanvasser", "https://www.ecanvasser.com", "https://app.ecanvasser.com",
     "Advocacy canvassing;Mobile data collection;Voter/supporter outreach", "YES", "YES",
     "sourceforge votervoice compare"),
    (50, "Handraiser", "https://www.handraiser.com", "https://www.handraiser.com",
     "Voter/advocate CRM;Multi-channel outreach;Campaign mobilization", "NO", "YES",
     "sourceforge votervoice compare"),
    # Nonprofit / fundraising mobile SMS (opt-in lists + text-to-action)
    (51, "GiveSmart (MobileCause)", "https://www.givesmart.com", "https://www.givesmart.com/login",
     "Text-to-give;Mobile messaging;Peer-to-peer;Donor engagement", "NO", "YES",
     "givesmart mobilecause blog; wildapricot fundraising software"),
    (52, "Mightycause", "https://mightycause.com", "https://mightycause.com/login",
     "Text-to-give;Keyword campaigns;Donor CRM;Automated marketing SMS", "YES", "YES",
     "mightycause text-to-give support; bloomerang text-to-give platforms"),
    (53, "GiveLively", "https://www.givelively.org", "https://www.givelively.org",
     "Text-to-donate;Mobile-first giving;Fundraising SMS", "YES", "YES",
     "bloomerang text-to-give platforms; emitrr nonprofit guide"),
    (54, "OneCause (Bonterra)", "https://www.onecause.com", "https://www.onecause.com",
     "Text-to-give;Mobile donation;Event fundraising SMS", "NO", "YES",
     "bloomerang text-to-give platforms; bonterra text-to-donate blog"),
    (55, "Network for Good (Bonterra)", "https://www.networkforgood.com", "https://www.networkforgood.com",
     "Bulk SMS;Text-to-give;Donor engagement", "NO", "YES",
     "bonterra text-to-donate blog"),
    (56, "DonorDrive", "https://www.donordrive.com", "https://www.donordrive.com",
     "Peer-to-peer fundraising;Mobile engagement;Event SMS", "NO", "YES",
     "emitrr nonprofit texting guide"),
    (57, "Qgiv", "https://www.qgiv.com", "https://www.qgiv.com",
     "Text-to-donate;Mobile fundraising;Donor outreach SMS", "NO", "YES",
     "bloomerang text-to-give platforms"),
    (58, "Givebutter", "https://givebutter.com", "https://givebutter.com",
     "Text-to-donate;Keyword giving;Supporter SMS (limited 2-way)", "YES", "YES",
     "rallycorp pricing guide; bonterra text-to-donate blog"),
    (59, "Pledge", "https://www.pledge.to", "https://www.pledge.to",
     "Text-to-give;Mobile fundraising;Cause SMS campaigns", "YES", "YES",
     "bonterra text-to-donate blog"),
    (60, "Snowball", "https://snowballfundraising.com", "https://snowballfundraising.com",
     "Text-to-give;Text-to-pledge;Mobile donor outreach", "YES", "YES",
     "bloomerang text-to-give platforms"),
    (61, "Donorbox", "https://donorbox.org", "https://donorbox.org",
     "Text-to-give;Mobile-optimized giving;Supporter messaging", "YES", "YES",
     "bloomerang text-to-give platforms"),
    (62, "Handbid", "https://www.handbid.com", "https://www.handbid.com",
     "Text2Give;Mobile auction/fundraising SMS", "NO", "YES",
     "bloomerang text-to-give platforms"),
    (63, "Bloomerang", "https://bloomerang.com", "https://crm.bloomerang.co",
     "Text fundraising;Donor CRM;Mobile giving integration", "NO", "YES",
     "bloomerang text-to-give platforms; zipdo nonprofit advocacy"),
    (64, "FRANSiS", "https://www.fransis.ai", "https://www.fransis.ai",
     "AI SMS for nonprofits;Advocacy outreach;Volunteer coordination;Text-to-donate", "NO", "YES",
     "fransis.ai; nonprofit text messaging platform guide"),
    (65, "CareMessage", "https://www.caremessage.org", "https://www.caremessage.org",
     "Nonprofit SMS outreach;Mass patient/supporter messaging;Two-way SMS", "NO", "YES",
     "fransis competitor comparison; safety-net engagement"),
    (66, "CharityEngine", "https://www.charityengine.com", "https://www.charityengine.com",
     "Nonprofit CRM;SMS fundraising;Advocacy communications", "NO", "YES",
     "bonterra text-to-donate blog"),
    (67, "Classy (GoFundMe Pro)", "https://www.classy.org", "https://www.classy.org",
     "Mobile fundraising;Text engagement;Nonprofit campaigns", "NO", "YES",
     "wildapricot fundraising software"),
    (68, "FrontStream", "https://www.frontstream.com", "https://www.frontstream.com",
     "Nonprofit SMS strategy;Mobile fundraising consulting ecosystem", "NO", "YES",
     "frontstream mobile SMS broadcast vs P2P article"),
    (69, "Smart As A Fox Mobile Messaging", "https://www.smartasafox.org", "https://www.smartasafox.org",
     "Mobile messaging strategy;Broadcast SMS for campaigns;Patch-through calling reselling", "NO", "YES",
     "smartasafox.org; frontstream article cites Revere/Mobile Commons peer set"),
    (70, "Revere (citizen advocacy app)", "https://revere.social", "https://revere.social",
     "Mobile advocacy actions;Tap-to-call legislators;Org-to-citizen mobilization", "YES", "YES",
     "revere.social; call-your-legislator ecosystem search"),
    # Church / community mobile engagement (same opt-in list + broadcast model)
    (71, "Clearstream", "https://clearstream.io", "https://my.clearstream.io",
     "Mass SMS;Text-to-join keywords;Two-way texting;Automated workflows", "YES", "YES",
     "clearstream.io; softwareworld upland alternatives"),
    (72, "Text In Church", "https://textinchurch.com", "https://textinchurch.com",
     "Church SMS;Group texting;Keyword opt-in;Planning Center sync", "YES", "YES",
     "threefold clearstream vs text in church comparison"),
    (73, "Gloo", "https://gloo.us", "https://gloo.us",
     "Church/community SMS;Member engagement;Planning Center texting", "YES", "YES",
     "threefold planning center texting comparison"),
    (74, "Subsplash", "https://subsplash.com", "https://dashboard.subsplash.com",
     "Church mobile app;Groups and messaging;Text giving", "NO", "YES",
     "subsplash.com; mosestab compare"),
    (75, "Tithe.ly", "https://tithe.ly", "https://tithe.ly",
     "Text giving;Church SMS;Mobile engagement", "YES", "YES",
     "bloomerang text-to-give platforms"),
    (76, "Rock RMS Texting integrations", "https://www.rockrms.com", "https://www.rockrms.com",
     "Church engagement;SMS integrations via partners;Member mobilization", "NO", "YES",
     "clearstream getapp integrations list"),
    # General SMS platforms with explicit advocacy/nonprofit/civic positioning
    (77, "EZ Texting", "https://www.eztexting.com", "https://app.eztexting.com",
     "Advocacy text campaigns;Text-to-join;Nonprofit SMS;P2P features", "YES", "YES",
     "eztexting advocacy text; selecthub mcommons alternatives; krowdbase"),
    (78, "SlickText", "https://www.slicktext.com", "https://www.slicktext.com/login",
     "Political broadcast SMS;P2P texting;Advocacy campaigns", "YES", "YES",
     "slicktext political SMS marketing 2026 guide"),
    (79, "SimpleTexting", "https://simpletexting.com", "https://app.simpletexting.com",
     "Mass texting;Nonprofit advocacy use;Two-way SMS", "YES", "YES",
     "selecthub mcommons alternatives; rallycorp pricing guide"),
    (80, "Textedly", "https://www.textedly.com", "https://www.textedly.com/login",
     "Mass SMS;Keyword campaigns;Nonprofit and advocacy use", "YES", "YES",
     "selecthub mcommons alternatives; krowdbase mcommons alternatives"),
    (81, "Text-Em-All", "https://www.text-em-all.com", "https://app.text-em-all.com",
     "Mass messaging;Nonprofit and advocacy alerts;Two-way texting", "YES", "YES",
     "selecthub mcommons alternatives"),
    (82, "Textmagic", "https://www.textmagic.com", "https://my.textmagic.com",
     "Bulk SMS;Supporter outreach;Nonprofit campaigns", "YES", "YES",
     "selecthub mcommons alternatives; saashub upland alternatives"),
    (83, "Trumpia", "https://www.trumpia.com", "https://www.trumpia.com",
     "SMS automation;Mass texting;Advocacy and nonprofit use", "NO", "YES",
     "selecthub mcommons alternatives (original list)"),
    (84, "Avochato", "https://www.avochato.com", "https://app.avochato.com",
     "Two-way SMS;CRM integrations;Organizing outreach", "YES", "YES",
     "selecthub mcommons alternatives; fransis competitor page"),
    (85, "TextUs", "https://textus.com", "https://app.textus.com",
     "Shared inbox SMS;Outreach teams;Advocacy and nonprofit use", "YES", "YES",
     "textus hustle vs ez texting blog"),
    (86, "Heymarket", "https://www.heymarket.com", "https://app.heymarket.com",
     "Team SMS;Broadcast and conversations;Mission-driven outreach", "YES", "YES",
     "selecthub SMS marketing compare list"),
    (87, "MessageDesk", "https://www.messagedesk.com", "https://app.messagedesk.com",
     "SMS inbox;Group texting;Community and nonprofit outreach", "YES", "YES",
     "selecthub SMS marketing compare list"),
    (88, "ProTexting", "https://www.protexting.com", "https://www.protexting.com",
     "SMS marketing;Keyword opt-in;Short codes;Mass texting", "YES", "YES",
     "selecthub SMS marketing compare list"),
    (89, "IRIO", "https://www.irio.com", "https://www.irio.com",
     "Mass SMS;Text notifications;Community outreach", "YES", "YES",
     "selecthub mcommons alternatives"),
    (90, "Community.com", "https://community.com", "https://community.com",
     "Politics and advocacy SMS;Two-way supporter messaging;ActBlue integration", "NO", "YES",
     "community.com politics-advocacy; actblue integration page"),
    (91, "Emitrr", "https://emitrr.com", "https://emitrr.com",
     "Text messaging;Nonprofit and advocacy client use", "YES", "YES",
     "emitrr nonprofit texting platforms 2025 blog"),
    (92, "TextBolt", "https://textbolt.com", "https://textbolt.com",
     "Nonprofit SMS;Keyword opt-in;Email-to-text broadcasts", "YES", "YES",
     "textbolt.com nonprofits"),
    (93, "ClickSend", "https://www.clicksend.com", "https://dashboard.clicksend.com",
     "Bulk SMS;Nonprofit and campaign messaging", "YES", "YES",
     "emitrr nonprofit guide; saashub upland alternatives"),
    (94, "Text Request", "https://www.textrequest.com", "https://app.textrequest.com",
     "Business and nonprofit SMS;Mass texting;Two-way inbox", "YES", "YES",
     "softwareworld upland alternatives"),
    (95, "CallFire", "https://www.callfire.com", "https://www.callfire.com/login",
     "Mass SMS;Voice and text;Nonprofit and political outreach", "YES", "YES",
     "mass_calling_platforms.csv"),
    (96, "DialMyCalls", "https://www.dialmycalls.com", "https://www.dialmycalls.com/login",
     "Mass SMS;Emergency and advocacy alerts;Text broadcasting", "YES", "YES",
     "mass_calling_platforms.csv"),
    (97, "Sakari", "https://www.sakari.io", "https://app.sakari.io",
     "Bulk SMS;Integrations;Nonprofit and advocacy outreach", "YES", "YES",
     "selecthub SMS marketing compare list"),
    (98, "Telerivet", "https://www.telerivet.com", "https://www.telerivet.com",
     "Advocacy SMS;Contact management;Mass messaging;Two-way dialogue", "YES", "YES",
     "telerivet.com solutions/advocacy"),
    (99, "FrontlineSMS", "https://www.frontlinesms.com", "https://www.frontlinesms.com",
     "SMS advocacy;Offline-capable;Nonprofit mass messaging", "YES", "PARTIAL",
     "zipdo nonprofit advocacy rankings (rank 6 SMS advocacy)"),
    (100, "Mobilize (Bonterra)", "https://www.bonterratech.com/product/mobilize", "https://www.mobilize.us",
     "Volunteer SMS reminders;Event mobilization;Advocacy org outreach", "YES", "YES",
     "bonterra mobilize product page; volunteer SMS reminders"),
]

VOCABULARY_GROUPS = [
    ("mobile advocacy / advocacy SMS platform", 18),
    ("Mobile Commons alternatives / Upland Mobile Messaging competitors", 14),
    ("civic engagement mobile CRM / supporter activation platform", 12),
    ("grassroots advocacy software SMS / public affairs mobilization", 16),
    ("nonprofit mass texting / broadcast SMS nonprofit", 15),
    ("political campaign mobile messaging / GOTV SMS", 12),
    ("text-to-action / text-to-join / mobile keyword advocacy", 10),
    ("call your legislator SMS / patch-through mobile advocacy", 8),
    ("digital organizing suite broadcast texting", 11),
    ("union member SMS / labor mobilization texting", 6),
    ("501(c)(3) and 501(c)(4) advocacy texting", 8),
    ("church/community SMS opt-in list (parallel use case)", 6),
    ("text-to-give / mobile fundraising SMS", 10),
    ("peer-to-peer texting advocacy (paired with broadcast like mcommons)", 9),
    ("association member mobilization SMS", 5),
]


def write_csv(path):
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow([
            "#", "Name", "Website_URL", "Login_URL", "Service_Type",
            "Self_Serve", "US_Focused", "Source_URL",
        ])
        for row in PLATFORMS:
            w.writerow(row)


def write_md(path):
    from pathlib import Path
    path = Path(path)
    lines = [
        "# Mobile Commons–Like Platforms (100 Services)",
        "",
        "Platforms for **advocacy, civic, political, nonprofit, union, and association mobile engagement** — especially **opt-in mass SMS**, **mobile supporter CRM**, **text-to-action**, **legislator contact**, **GOTV**, and **mobile fundraising** workflows comparable to [Mobile Commons](https://www.mobilecommons.com).",
        "",
        "## Alternate vocabulary used to find services",
        "",
    ]
    for term, _ in VOCABULARY_GROUPS:
        lines.append(f"- {term}")
    lines.extend(["", "## Platform list", ""])
    for num, name, url, login, services, self_serve, us, source in PLATFORMS:
        lines.extend([
            f"**{num}. {name}**",
            f"- URL: {url}",
            f"- Login: {login}",
            f"- Services: {services}",
            f"- Self-serve: {self_serve}",
            f"- US Focused: {us}",
            f"- Source: {source}",
            "",
        ])
    path.write_text("\n".join(lines), encoding="utf-8")


def write_stats(path):
    from pathlib import Path
    path = Path(path)
    cats = Counter()
    for _, _, _, _, services, self_serve, us, _ in PLATFORMS:
        for part in services.split(";"):
            key = part.strip()
            if key:
                cats[key] += 1
    self_yes = sum(1 for p in PLATFORMS if p[5] == "YES")
    us_yes = sum(1 for p in PLATFORMS if p[6] == "YES")
    lines = [
        "Mobile Commons–Like Platform Research — Statistics",
        "=" * 55,
        f"Total platforms: {len(PLATFORMS)}",
        f"Self-serve signup (YES): {self_yes}",
        f"US-focused (YES): {us_yes}",
        f"US-focused (PARTIAL): {sum(1 for p in PLATFORMS if p[6] == 'PARTIAL')}",
        "",
        "Inclusion bar (same purposes as Mobile Commons):",
        "- Opt-in mobile supporter/advocate lists with broadcast SMS (A2P) and/or",
        "  integrated advocacy mobile CRM (not generic CPaaS-only)",
        "- Text-to-action: petitions, legislator email/call/SMS, GOTV, fundraising",
        "- Built for nonprofits, campaigns, unions, associations, advocacy orgs, or",
        "  churches/community orgs using the same list-building + blast model",
        "",
        "Explicitly excluded from this list:",
        "- Twilio, Plivo, Bandwidth (raw CPaaS without advocacy product surface)",
        "- Pure retail/e-commerce SMS (Attentive, Postscript, etc.)",
        "- Pure email-only CRMs without SMS/mobile engagement path",
        "",
        "Alternate vocabulary search groups (brainstorm → queries):",
    ]
    for term, count in VOCABULARY_GROUPS:
        lines.append(f"  - {term} (~{count} targeted searches)")
    lines.extend([
        "",
        "Top service tags (platform may appear in multiple):",
    ])
    for tag, count in cats.most_common(25):
        lines.append(f"  {count:3d}  {tag}")
    lines.extend([
        "",
        "Category breakdown (primary fit):",
        "  25  Core mobile advocacy CRM peers (direct mcommons category)",
        "  25  Digital organizing suites (broadcast + P2P + CRM overlap)",
        "  20  Nonprofit/fundraising mobile SMS",
        "   6  Church/community mobile engagement",
        "  24  General SMS with explicit advocacy/nonprofit positioning",
        "",
        "Legacy / merged names worth knowing:",
        "  - Phone2Action → Capitol Canary → Quorum Grassroots",
        "  - Strive Messaging → Ascend",
        "  - Outvote → Impactive → ActBlue Field Tools",
        "  - MobileCause → GiveSmart (Community Brands / Momentive)",
        "  - Revere Suite (legacy broadcast advocacy CRM; cited with Mobile Commons",
        "    in organizer literature; successor vendor landscape now Ascend/Rally/etc.)",
        "",
        "Output files:",
        "  - mcommons_like_platforms.csv",
        "  - mcommons_like_platforms.md",
        "  - mcommons_like_platforms_stats.txt",
    ])
    path.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    base = "/workspace"
    write_csv(f"{base}/mcommons_like_platforms.csv")
    write_md(f"{base}/mcommons_like_platforms.md")
    write_stats(f"{base}/mcommons_like_platforms_stats.txt")
    print(f"Wrote {len(PLATFORMS)} platforms")
